name: build TPDM Minimal Template sqlServer

on:
  workflow_dispatch:
    inputs:
      version_suite:
        type: number
        required: true
      version_major:
        type: number
        required: true
      version_minor:
        type: number
        required: true
      standard_version:
        type: string
        required: true

env:
  version_suite: 3
  version_major: 5
  version_minor: 3
  tpdm_version: 1.1.0
  standard_version: v3.3.1-b

jobs:
  build:
    runs-on: windows-latest
          
    steps:
      - name: Set env variables
        shell: pwsh
        run: |
          $version_patch = ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            echo "version_informational=${{ format('v{0}.{1}', github.event.inputs.version_major , github.event.inputs.version_minor ) }}" >> $env:GITHUB_ENV
            echo ("version_core=${{ format('{0}.{1}', github.event.inputs.version_major, github.event.inputs.version_minor) }}" + "$version_patch") >> $env:GITHUB_ENV
          } else {
            echo "version_informational=${{ format('v{0}.{1}', env.version_major , env.version_minor ) }}" >> $env:GITHUB_ENV
            echo ("version_core=${{ format('{0}.{1}', env.version_major, env.version_minor) }}" + "$version_patch") >> $env:GITHUB_ENV
          }
          echo "temp=${{ github.workspace }}\temp" >> $env:GITHUB_ENV
          
      - name: Debugging with tmate
        # You may pin to the exact commit or the version.
        # uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270
        uses: mxschmitt/action-tmate@v3.11
        with:
          timeout-minutes: 15
          
      - name: Git long filename support
        run: |
          git config --system core.longpaths true
          gci env: | where name -like '*version*'
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS-Implementation
        
      - name: Workarounds for file copy
        run: |
          (get-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1 -Raw).replace('-Destination "$directory\$xmlFile"', '-Destination "$directory\$($xmlFile.Name)"').replace('-Destination "$directory\$xsdFile"', '-Destination "$directory\$($xsdFile.Name)"') | set-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS

      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard
          ref: ${{ env.standard_version }}
          path: Ed-Fi-ODS-Standard

      - uses: actions/checkout@v2
        with:
          path: Ed-Fi-TPDM-Extension
          
      - name: Install SQL Server
        run: choco install sql-server-2019 
          
      - name: Replace package name in packages config
        run: |
          (Get-Content configuration.packages.json) `
          -replace 'EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Core.${{ env.tpdm_version }}', 'EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}' `
          -replace '"PackageVersion": "5.3.38",','"PackageVersion": "5.3.67",' |
          Out-File configuration.packages.json
        working-directory: ./Ed-Fi-ODS-Implementation
        
      - name: Replace package name in create script
        run: |
          (Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1) `
          -replace 'EdFi.Ods.Minimal.Template.TPDM.Core', 'EdFi.Ods.Minimal.Template.TPDM.Community' ` |
          Out-File ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
          
      - name: Remove Ed-Fi Databases
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module ./Ed-Fi-ODS-Implementation/logistics/scripts/modules/build-management.psm1
          Remove-EdFiDatabases -Force
      
      - name: Initialize-DevelopmentEnvironment
        run: |
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Initialize-DevelopmentEnvironment -UsePlugins -NoDeploy
        working-directory: ./Ed-Fi-ODS-Implementation
          
      - name: Create Database Template
        run: |
          Import-Module -Force -Scope Global ${{ github.workspace }}\Ed-Fi-ODS-Implementation\DatabaseTemplate\Modules\create-tpdm-minimal-template.psm1
          Initialize-TPDMMinimalTemplate -samplePath "D:\a\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Extension\"
        working-directory: ./Ed-Fi-TPDM-Extension

      - name: Pack
        run: | 
          nuget pack ${{ github.workspace }}/Ed-Fi-ODS-Implementation/DatabaseTemplate/Database/EdFi.Ods.Minimal.Template.TPDM.Community.nuspec `
          -OutputDirectory ${{ github.workspace }}/NugetPackages `
          -Version ${{ env.version_core }} `
          -Properties configuration=release `
          -Properties "authors=Ed-Fi Alliance" `
          -Properties "owners=Ed-Fi Alliance" `
          -Properties "copyright=Copyright ©Ed-Fi Alliance, LLC. 2020" `
          -Properties id=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }} `
          -Properties title=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }} `
          -Properties "description=EdFi Ods Minimal Template TPDM Community Database" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/Ed-Fi-TPDM-Extension
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
          path: NugetPackages\EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
