name: build TPDM Minimal Template postgreSQL

on:
  workflow_dispatch:

env:
  version_suite: 3
  version_major: 5
  version_minor: 3
  version_patch: ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
  tpdm_version: 1.1.0
  standard_version: v3.3.1-b

jobs:
  build:
    runs-on: windows-latest
          
    steps:
      - name: Set env variables
        shell: pwsh
        run: |
          echo "version_informational=${{ format('v{0}.{1}', env.version_major , env.version_minor ) }}" >> $env:GITHUB_ENV
          echo "version_core=${{ format('{0}.{1}.{2}', env.version_major, env.version_minor , env.version_patch) }}" >> $env:GITHUB_ENV
          echo "temp=${{ github.workspace }}\temp" >> $env:GITHUB_ENV
          
      - name: Git long filename support
        run: git config --system core.longpaths true
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS-Implementation
        
      - name: Workarounds for file copy
        run: |
          (get-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1 -Raw).replace('-Destination "$directory\$xmlFile"', '-Destination "$directory\$($xmlFile.Name)"').replace('-Destination "$directory\$xsdFile"', '-Destination "$directory\$($xsdFile.Name)"') | set-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1
        
      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.version_informational }}
          path: Ed-Fi-ODS

      - uses: actions/checkout@v2
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Standard
          ref: ${{ env.standard_version }}
          path: Ed-Fi-ODS-Standard

      - uses: actions/checkout@v2
        with:
          path: Ed-Fi-TPDM-Extension
          
      - name: Install PostgreSQL
        run: | 
          choco install postgresql11
          (Get-Content "C:\Program Files\PostgreSQL\11\data\pg_hba.conf").replace 'md5','trust' | Out-File "C:\Program Files\PostgreSQL\11\data\pg_hba.conf"
          Restart-Service postgresql*
          
      - name: Replace package name in packages config
        run: |
          (Get-Content configuration.packages.json) `
          -replace 'EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Core.${{ env.tpdm_version }}', 'EdFi.Suite${{ env.version_suite }}.Ods.Extensions.TPDM.Community.${{ env.tpdm_version }}' `
          -replace '"PackageVersion": "5.3.38",','"PackageVersion": "5.3.67",' |
          Out-File configuration.packages.json
        working-directory: ./Ed-Fi-ODS-Implementation
        
      - name: Replace package name in create script
        run: |
          (Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1) `
          -replace 'EdFi.Ods.Minimal.Template.TPDM.Core', 'EdFi.Ods.Minimal.Template.TPDM.Community' ` |
          Out-File ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
          
      - name: Remove Ed-Fi Databases
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module ./Ed-Fi-ODS-Implementation/logistics/scripts/modules/build-management.psm1
          Remove-EdFiDatabases -Force -Engine PostgreSQL
      
      - name: Initialize-DevelopmentEnvironment
        run: |
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Initialize-DevelopmentEnvironment -UsePlugins -NoDeploy -Engine PostgreSQL
        working-directory: ./Ed-Fi-ODS-Implementation
          
      - name: Create Database Template
        run: |
          Import-Module -Force -Scope Global ${{ github.workspace }}\Ed-Fi-ODS-Implementation\DatabaseTemplate\Modules\create-tpdm-minimal-template.psm1
          Initialize-TPDMMinimalTemplate -samplePath "D:\a\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Extension\"
        working-directory: ./Ed-Fi-TPDM-Extension

      - name: Pack
        run: | 
          nuget pack ${{ github.workspace }}/Ed-Fi-ODS-Implementation/DatabaseTemplate/Database/EdFi.Ods.Minimal.Template.TPDM.Community.PostgreSQL.nuspec `
          -OutputDirectory ${{ github.workspace }}/NugetPackages `
          -Version ${{ env.version_core }} `
          -Properties configuration=release `
          -Properties "authors=Ed-Fi Alliance" `
          -Properties "owners=Ed-Fi Alliance" `
          -Properties "copyright=Copyright ©Ed-Fi Alliance, LLC. 2020" `
          -Properties id=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }}.PostgreSQL `
          -Properties title=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.${{ env.tpdm_version }}.PostgreSQL `
          -Properties "description=EdFi Ods Minimal Template TPDM Community Database for PostgreSQL" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/Ed-Fi-TPDM-Extension
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          name: EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
          path: NugetPackages\EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
