name: build TPDM Minimal Template postgreSQL

on:
  workflow_dispatch:
    inputs:
      tpdm_version:
        type: string
        required: false
        description: "tpdm_version: TPDM version as noted in the Community Extension built nuget package artifact. Default: 1.1.0"
      Ed-Fi-ODS-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-ref: checks out the specified branch/tag of the Ed-Fi-ODS repo. Default branch if not specified."
      Ed-Fi-ODS-Implementation-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-Implementation-ref: checks out the specified branch/tag of the Ed-Fi-ODS-Implementation repo. Default branch if not specified."

env:
  tpdm_version: "1.1.0"
  ods_ref: ""
  ods_ref_implementation: ""


jobs:
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    with:
      config-file-path: ./.github/workflows/bidi-scanner/config.json
    
  build:
    runs-on: windows-latest
          
    steps:
      - name: Set env variables
        shell: pwsh
        run: |
          $version_patch = ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
          if ("${{ github.event.inputs.tpdm_version  }}" -ne "") {
            echo "tpdm_version=${{ github.event.inputs.tpdm_version }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-ref  }}" -ne "") {
            echo "ods_ref=${{ github.event.inputs.Ed-Fi-ODS-ref }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref  }}" -ne "") {
            echo "ods_ref_implementation=${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref }}" >> $env:GITHUB_ENV
          }
          echo "temp=${{ github.workspace }}\temp" >> $env:GITHUB_ENV
          
      - name: Git long filename support
        run: git config --system core.longpaths true
        

      - name: Ed-Fi-ODS
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.ods_ref }}
          path: Ed-Fi-ODS

      - name: Ed-Fi-ODS-Implementation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.ods_ref_implementation }}
          path: Ed-Fi-ODS-Implementation
          
      - name: Ed-Fi-Extension
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: Ed-Fi-TPDM-Extension   
          
      - name: Workaround for duplicake package references in EdFi.Ods.Sandbox.csproj
        run: |
          $f = Get-Content .\EdFi.Ods.Sandbox.csproj -Raw
          $first_part = $f | Select-String -Pattern '(?s)^.*?(?=\<PackageReference)' | Foreach {$_.matches.value} | Out-String
          $unique_packages = $f | Select-String -allmatches -Pattern '(?m)^.*?<PackageReference.*$' | Foreach {$_.Matches.value} | Select-Object -Unique | Out-String
          $last_part = $f | Select-String -Pattern '(?s)\<\/ItemGroup.*' | Foreach {$_.matches.value} | Out-String
          $first_part + $unique_packages + $last_part > .\EdFi.Ods.Sandbox.csproj
        working-directory: Ed-Fi-ODS\Application\EdFi.Ods.Sandbox
        
      - name: Workaround for file copy
        run: |
          (get-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1 -Raw).replace('-Destination "$directory\$xmlFile"', '-Destination "$directory\$($xmlFile.Name)"').replace('-Destination "$directory\$xsdFile"', '-Destination "$directory\$($xsdFile.Name)"') | set-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1
      
      - name: Replace package name and version in packages config
        run: |
          (Get-Content configuration.packages.json -Raw) `
            -replace '(?ism)(?<="tpdm")(.*?)\d(.*?)Core\.(\d+.\d+\.\d+)(.*?)\d+.\d+\.\d+' `
            , '${1}3$2Community.${{ env.tpdm_version }}${4}${{ env.tpdm_package_version }}' `
            | Out-File configuration.packages.json
        working-directory: ./Ed-Fi-ODS-Implementation
        
      - name: Install PostgreSQL
        run: | 
          choco install postgresql11 --no-progress
          Stop-Service postgresql*
          Set-Content -Path "C:\Program Files\PostgreSQL\11\data\pg_hba.conf" -Value 'host    all    all    all    trust'
          Start-Service postgresql-x64-11
        
      - name: Replace package name in create script
        run: |
          (Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1) `
          -replace 'EdFi.Ods.Minimal.Template.TPDM.Core', 'EdFi.Ods.Minimal.Template.TPDM.Community' ` |
          Out-File ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-minimal-template.psm1
          
      - name: Remove Ed-Fi Databases
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module ./Ed-Fi-ODS-Implementation/logistics/scripts/modules/build-management.psm1
          Remove-EdFiDatabases -Force -Engine PostgreSQL
      
      - name: Initialize-DevelopmentEnvironment
        run: |
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Initialize-DevelopmentEnvironment -UsePlugins -NoDeploy -Engine PostgreSQL
        working-directory: ./Ed-Fi-ODS-Implementation
          
      - name: Create Database Template
        run: |
          Import-Module -Force -Scope Global ${{ github.workspace }}\Ed-Fi-ODS-Implementation\DatabaseTemplate\Modules\create-tpdm-minimal-template.psm1
          Initialize-TPDMMinimalTemplate -samplePath "D:\a\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Extension\"  -Engine PostgreSQL
        working-directory: ./Ed-Fi-TPDM-Extension

      - name: Pack
        run: | 
          nuget pack ${{ github.workspace }}/Ed-Fi-ODS-Implementation/DatabaseTemplate/Database/EdFi.Ods.Minimal.Template.TPDM.Community.PostgreSQL.nuspec `
          -OutputDirectory ${{ github.workspace }}/NugetPackages `
          -Version ${{ env.version_core }} `
          -Properties configuration=release `
          -Properties "authors=Ed-Fi Alliance" `
          -Properties "owners=Ed-Fi Alliance" `
          -Properties "copyright=Copyright ©Ed-Fi Alliance, LLC. 2020" `
          -Properties id=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }} `
          -Properties title=EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }} `
          -Properties "description=EdFi Ods Minimal Template TPDM Community Database for PostgreSQL" `
          -NoPackageAnalysis -NoDefaultExcludes
        working-directory: ${{ github.workspace }}/Ed-Fi-TPDM-Extension
        
      - name: Upload artifact
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
          path: NugetPackages\EdFi.Suite${{ env.version_suite }}.Ods.Minimal.Template.TPDM.Community.PostgreSQL.${{ env.tpdm_version }}.${{ env.version_core }}.nupkg
