name: Deploy TPDM Populated Template postgreSQL

on: 
  workflow_dispatch:

permissions: read-all
  
env:
  AZURE_ARTIFACTS_FEED_URL: https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json
  NUGET_AUTH_TOKEN: ${{ secrets.TPDM_AA_PUBLISH }} 

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@a71d1eb2c86af85faa8c772c03fb365e377e45ea
        with:
          source-url: ${{ env.AZURE_ARTIFACTS_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TPDM_AA_PUBLISH }} 

      - name: Download package
        uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22
        with:
          workflow: build-populated-template-postgreSQL.yml
          path: publish
      
      - name: Publish
        run: dotnet nuget push publish/*/*.nupkg --api-key AzureArtifacts
