name: Test Nuget package

on:
  workflow_dispatch:
    inputs:
      tpdm_version:
        type: string
        description: "tpdm_version: TPDM version as noted in the Community Extension built nuget package artifact."
      Ed-Fi-ODS-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-ref: checks out the specified branch/tag of the Ed-Fi-ODS repo"
      Ed-Fi-ODS-Implementation-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-Implementation-ref: checks out the specified branch/tag of the Ed-Fi-ODS-Implementation repo"

env:
  tpdm_version: 1.1.0
  ods_ref: "ODS-5569"
  ods_ref_implementation: "ODS-5569"

jobs:
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    
  build:
    runs-on: windows-latest
          
    steps:
      - name: Set env variables
        shell: pwsh
        run: |
          $version_patch = ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
          if ("${{ github.event.inputs.Ed-Fi-ODS-ref  }}" -ne "") {
            echo "ods_ref=${{ github.event.inputs.Ed-Fi-ODS-ref }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref  }}" -ne "") {
            echo "ods_ref_implementation=${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref }}" >> $env:GITHUB_ENV
          }
          echo "temp=${{ github.workspace }}\temp" >> $env:GITHUB_ENV
          
      - name: Git long filename support
        run: git config --system core.longpaths true
        

      - name: Ed-Fi-ODS
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.ods_ref }}
          path: Ed-Fi-ODS

      - name: Ed-Fi-ODS-Implementation
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.ods_ref_implementation }}
          path: Ed-Fi-ODS-Implementation
          

      - name: Ed-Fi-Extension
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          path: Ed-Fi-TPDM-Extension   
          
      - name: Workaround for duplicake package references in EdFi.Ods.Sandbox.csproj
        run: |
          $f = Get-Content .\EdFi.Ods.Sandbox.csproj -Raw
          $first_part = $f | Select-String -Pattern '(?s)^.*?(?=\<PackageReference)' | Foreach {$_.matches.value} | Out-String
          $unique_packages = $f | Select-String -allmatches -Pattern '(?m)^.*?<PackageReference.*$' | Foreach {$_.Matches.value} | Select-Object -Unique | Out-String
          $last_part = $f | Select-String -Pattern '(?s)\<\/ItemGroup.*' | Foreach {$_.matches.value} | Out-String
          $first_part + $unique_packages + $last_part > .\EdFi.Ods.Sandbox.csproj
        working-directory: Ed-Fi-ODS\Application\EdFi.Ods.Sandbox
        
      - name: Download TPDM-Community-Extension Artifact
        uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22
        with:
          workflow: build-nuget-package.yml
          repo: Ed-Fi-Exchange-OSS/TPDM-Community-Extension
          path: Artifact

      - name: Rename Artifact folder
        run: |
          get-childitem -Path . -Directory -Filter "*" | Move-Item -Destination "NugetPackages"
        working-directory: Artifact

      - name: Replace package name and version in packages config
        run: |
          $PackageSource = ('${{ github.workspace }}' -Replace '\\', '/') + '/Artifact/NugetPackages/"'
          (Get-Content configuration.packages.json -Raw) `
            -replace '(?ism)(?<="tpdm")(.*?)\d(.*?)Core\.(\d+.\d+\.\d+)(.*?)\d+.\d+\.\d+(.*?)https.*?(")' `
            , "`${1}3`$2Community.${{ env.tpdm_version }}`${5}$PackageSource" `
            | Out-File configuration.packages.json
          (Get-Content configuration.packages.json) | sls '"tpdm"' -Context 0,3
        working-directory: Ed-Fi-ODS-Implementation
          
        
      - name: Workaround for file copy
        run: |
          (get-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1 -Raw).replace('-Destination "$directory\$xmlFile"', '-Destination "$directory\$($xmlFile.Name)"').replace('-Destination "$directory\$xsdFile"', '-Destination "$directory\$($xsdFile.Name)"') | set-content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-database-template.psm1
      
      - name: Replace package name in create script
        run: |
          (Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-template.psm1) `
          -replace 'EdFi.Ods.Populated.Template.TPDM.Core', 'EdFi.Ods.Populated.Template.TPDM.Community' ` |
          Out-File ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-template.psm1
      
      - name: Install SQL Server
        run: choco install sql-server-2019 --no-progress --params="'/IgnorePendingReboot'"
          
      - name: Remove Ed-Fi Databases
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module ./Ed-Fi-ODS-Implementation/logistics/scripts/modules/build-management.psm1
          Remove-EdFiDatabases -Force
      
      - name: Initialize-DevelopmentEnvironment
        run: |
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Initialize-DevelopmentEnvironment -UsePlugins -NoDeploy
        working-directory: ./Ed-Fi-ODS-Implementation
          
      - name: Create Database Template
        run: |
          Import-Module -Force -Scope Global ${{ github.workspace }}\Ed-Fi-ODS-Implementation\DatabaseTemplate\Modules\create-tpdm-template.psm1
          Initialize-TPDMTemplate -samplePath "D:\a\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Extension\"
        working-directory: ./Ed-Fi-TPDM-Extension
