name: Test Community Extension package (unpublished)

on:
  workflow_dispatch:
    inputs:
      tpdm_version:
        type: string
        required: false
        description: "tpdm_version: TPDM version as noted in the Community Extension built nuget package artifact. Default: 1.2.0"
      Ed-Fi-ODS-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-ref: checks out the specified branch/tag of the Ed-Fi-ODS repo. Default branch if not specified."
      Ed-Fi-ODS-Implementation-ref:
        type: string
        required: false
        description: "Ed-Fi-ODS-Implementation-ref: checks out the specified branch/tag of the Ed-Fi-ODS-Implementation repo. Default branch if not specified."

env:
  tpdm_version: "1.2.0"
  ods_ref: ""
  ods_ref_implementation: ""

jobs:
  ed-fi-repository-scanner:    
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@main
    with:
     config-file-path: ./.github/workflows/bidi-scanner/config.json
    
  build:
    runs-on: windows-latest
          
    steps:
      - name: Set env variables
        shell: pwsh
        run: |
          $version_patch = ${{ format('{0}{1}', github.run_number , github.run_attempt) }}
          if ("${{ github.event.inputs.tpdm_version  }}" -ne "") {
            echo "tpdm_version=${{ github.event.inputs.tpdm_version }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-ref  }}" -ne "") {
            echo "ods_ref=${{ github.event.inputs.Ed-Fi-ODS-ref }}" >> $env:GITHUB_ENV
          }
          if ("${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref  }}" -ne "") {
            echo "ods_ref_implementation=${{ github.event.inputs.Ed-Fi-ODS-Implementation-ref }}" >> $env:GITHUB_ENV
          }
          echo "temp=${{ github.workspace }}\temp" >> $env:GITHUB_ENV
          
      - name: Git long filename support
        run: git config --system core.longpaths true

      - name: Ed-Fi-ODS
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS
          ref: ${{ env.ods_ref }}
          path: Ed-Fi-ODS

      - name: Ed-Fi-ODS-Implementation
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-ODS-Implementation
          ref: ${{ env.ods_ref_implementation }}
          path: Ed-Fi-ODS-Implementation
          
      - name: Ed-Fi-Extension
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          path: Ed-Fi-TPDM-Extension   
          
      - name: Download TPDM-Community-Extension Artifact
        uses: dawidd6/action-download-artifact@1cf11afe3f1874cee82a8d5a2b45c0fd63f0fa22
        with:
          workflow: "Pkg EdFi.Ods.Extensions.TPDM.yml"
          repo: Ed-Fi-Exchange-OSS/TPDM-Community-Extension
          path: Artifact

      - name: Rename Artifact folder
        run: |
          get-childitem -Path . -Directory -Filter "*" | Move-Item -Destination "NugetPackages"
        working-directory: Artifact

      - name: Replace package name and version in packages config
        run: |
          $PackageSource = ('${{ github.workspace }}' -Replace '\\', '/') + '/Artifact/NugetPackages/"'
          (Get-Content configuration.packages.json -Raw) `
            -replace '(?ism)(EdFi\.Suite3\.Ods\.Extensions\.TPDM)\.Core\.({ExtensionVersion}\.Standard\.{StandardVersion}).*?(PackageSource\"\:.*?\},)' `
            , "`${1}.Community.`$2`",`"PackageSource`":`"$PackageSource}," `
            | Out-File configuration.packages.json
          (Get-Content configuration.packages.json) | sls '"tpdm"' -Context 0,3
        working-directory: Ed-Fi-ODS-Implementation

      - name: Add tpdm_version to valid set
        run: |
          (Get-Content .\Application\SolutionScripts\InitializeDevelopmentEnvironment.psm1 -Raw) `
            -replace "(ValidateSet\()(.*?)(\))", '${1}$2,''${{ env.tpdm_version }}''$3' ` |
            Out-File .\Application\SolutionScripts\InitializeDevelopmentEnvironment.psm1
          (Get-Content .\Application\SolutionScripts\InitializeDevelopmentEnvironment.psm1) | sls 'ExtensionVersion' -Context 1,0
        working-directory: Ed-Fi-ODS-Implementation
          
      - name: Replace package name in create script
        run: |
          ((Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-template.psm1) `
          -replace 'Core', 'Community') -replace "(extensionVersion\s+\=\s+\').*?(\')", '${1}${{ env.tpdm_version }}$2' ` |
          Out-File ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-template.psm1
          (Get-Content ./Ed-Fi-ODS-Implementation/DatabaseTemplate/Modules/create-tpdm-template.psm1) | sls 'ExtensionVersion' -Context 0,3
      
      - name: Install SQL Server
        run: choco install sql-server-2019 --no-progress --params="'/IgnorePendingReboot'"
          
      - name: Remove Ed-Fi Databases
        run: |
          $ErrorActionPreference = 'Stop'
          Import-Module ./Ed-Fi-ODS-Implementation/logistics/scripts/modules/build-management.psm1
          Remove-EdFiDatabases -Force
      
      - name: Initialize-DevelopmentEnvironment
        run: |
          $ErrorActionPreference = 'Stop'
          ./Initialize-PowershellForDevelopment.ps1
          Initialize-DevelopmentEnvironment -UsePlugins -NoDeploy -ExtensionVersion "${{ env.tpdm_version }}"
        working-directory: ./Ed-Fi-ODS-Implementation
          
      - name: Create Database Template
        run: |
          Import-Module -Force -Scope Global ${{ github.workspace }}\Ed-Fi-ODS-Implementation\DatabaseTemplate\Modules\create-tpdm-template.psm1
          Initialize-TPDMTemplate -samplePath "D:\a\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Community-Artifacts\Ed-Fi-TPDM-Extension\" -ExtensionVersion "${{ env.tpdm_version }}"
        working-directory: ./Ed-Fi-TPDM-Extension
